//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapp_ui.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/StudentXchange")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private webapp_ui.ServiceReference1.BillingAddress[] BillingAddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private webapp_ui.ServiceReference1.ORDER[] ORDERsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private webapp_ui.ServiceReference1.Product[] ProductsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public webapp_ui.ServiceReference1.BillingAddress[] BillingAddresses {
            get {
                return this.BillingAddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingAddressesField, value) != true)) {
                    this.BillingAddressesField = value;
                    this.RaisePropertyChanged("BillingAddresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public webapp_ui.ServiceReference1.ORDER[] ORDERs {
            get {
                return this.ORDERsField;
            }
            set {
                if ((object.ReferenceEquals(this.ORDERsField, value) != true)) {
                    this.ORDERsField = value;
                    this.RaisePropertyChanged("ORDERs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public webapp_ui.ServiceReference1.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillingAddress", Namespace="http://schemas.datacontract.org/2004/07/StudentXchange")]
    [System.SerializableAttribute()]
    public partial class BillingAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private webapp_ui.ServiceReference1.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((this.PostalCodeField.Equals(value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public webapp_ui.ServiceReference1.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ORDER", Namespace="http://schemas.datacontract.org/2004/07/StudentXchange")]
    [System.SerializableAttribute()]
    public partial class ORDER : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IsboughtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private webapp_ui.ServiceReference1.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private webapp_ui.ServiceReference1.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Isbought {
            get {
                return this.IsboughtField;
            }
            set {
                if ((this.IsboughtField.Equals(value) != true)) {
                    this.IsboughtField = value;
                    this.RaisePropertyChanged("Isbought");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public webapp_ui.ServiceReference1.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public webapp_ui.ServiceReference1.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/StudentXchange")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private webapp_ui.ServiceReference1.CartItem[] CartItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private webapp_ui.ServiceReference1.Category CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlThumbnail1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlThumbnail2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlThumbnail3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private webapp_ui.ServiceReference1.ORDER[] ORDERsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private webapp_ui.ServiceReference1.PriceOffer[] PriceOffersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private webapp_ui.ServiceReference1.Review[] ReviewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private webapp_ui.ServiceReference1.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public webapp_ui.ServiceReference1.CartItem[] CartItems {
            get {
                return this.CartItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.CartItemsField, value) != true)) {
                    this.CartItemsField = value;
                    this.RaisePropertyChanged("CartItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public webapp_ui.ServiceReference1.Category Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((object.ReferenceEquals(this.DateCreatedField, value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrlThumbnail1 {
            get {
                return this.ImageUrlThumbnail1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlThumbnail1Field, value) != true)) {
                    this.ImageUrlThumbnail1Field = value;
                    this.RaisePropertyChanged("ImageUrlThumbnail1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrlThumbnail2 {
            get {
                return this.ImageUrlThumbnail2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlThumbnail2Field, value) != true)) {
                    this.ImageUrlThumbnail2Field = value;
                    this.RaisePropertyChanged("ImageUrlThumbnail2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrlThumbnail3 {
            get {
                return this.ImageUrlThumbnail3Field;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlThumbnail3Field, value) != true)) {
                    this.ImageUrlThumbnail3Field = value;
                    this.RaisePropertyChanged("ImageUrlThumbnail3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public webapp_ui.ServiceReference1.ORDER[] ORDERs {
            get {
                return this.ORDERsField;
            }
            set {
                if ((object.ReferenceEquals(this.ORDERsField, value) != true)) {
                    this.ORDERsField = value;
                    this.RaisePropertyChanged("ORDERs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public webapp_ui.ServiceReference1.PriceOffer[] PriceOffers {
            get {
                return this.PriceOffersField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceOffersField, value) != true)) {
                    this.PriceOffersField = value;
                    this.RaisePropertyChanged("PriceOffers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public webapp_ui.ServiceReference1.Review[] Reviews {
            get {
                return this.ReviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewsField, value) != true)) {
                    this.ReviewsField = value;
                    this.RaisePropertyChanged("Reviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public webapp_ui.ServiceReference1.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/StudentXchange")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private webapp_ui.ServiceReference1.Product[] ProductsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public webapp_ui.ServiceReference1.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartItem", Namespace="http://schemas.datacontract.org/2004/07/StudentXchange")]
    [System.SerializableAttribute()]
    public partial class CartItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private webapp_ui.ServiceReference1.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cartIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string datecreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int productIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int qtyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((this.ItemIdField.Equals(value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public webapp_ui.ServiceReference1.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cartId {
            get {
                return this.cartIdField;
            }
            set {
                if ((object.ReferenceEquals(this.cartIdField, value) != true)) {
                    this.cartIdField = value;
                    this.RaisePropertyChanged("cartId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string datecreated {
            get {
                return this.datecreatedField;
            }
            set {
                if ((object.ReferenceEquals(this.datecreatedField, value) != true)) {
                    this.datecreatedField = value;
                    this.RaisePropertyChanged("datecreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int productId {
            get {
                return this.productIdField;
            }
            set {
                if ((this.productIdField.Equals(value) != true)) {
                    this.productIdField = value;
                    this.RaisePropertyChanged("productId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int qty {
            get {
                return this.qtyField;
            }
            set {
                if ((this.qtyField.Equals(value) != true)) {
                    this.qtyField = value;
                    this.RaisePropertyChanged("qty");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriceOffer", Namespace="http://schemas.datacontract.org/2004/07/StudentXchange")]
    [System.SerializableAttribute()]
    public partial class PriceOffer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private webapp_ui.ServiceReference1.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Discount {
            get {
                return this.DiscountField;
            }
            set {
                if ((this.DiscountField.Equals(value) != true)) {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((object.ReferenceEquals(this.EndDateField, value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public webapp_ui.ServiceReference1.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((object.ReferenceEquals(this.StartDateField, value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Review", Namespace="http://schemas.datacontract.org/2004/07/StudentXchange")]
    [System.SerializableAttribute()]
    public partial class Review : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private webapp_ui.ServiceReference1.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StarsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public webapp_ui.ServiceReference1.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Stars {
            get {
                return this.StarsField;
            }
            set {
                if ((this.StarsField.Equals(value) != true)) {
                    this.StarsField = value;
                    this.RaisePropertyChanged("Stars");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Register", ReplyAction="http://tempuri.org/IService/RegisterResponse")]
        int Register(webapp_ui.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Register", ReplyAction="http://tempuri.org/IService/RegisterResponse")]
        System.Threading.Tasks.Task<int> RegisterAsync(webapp_ui.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Login", ReplyAction="http://tempuri.org/IService/LoginResponse")]
        bool Login(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Login", ReplyAction="http://tempuri.org/IService/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/closeAcc", ReplyAction="http://tempuri.org/IService/closeAccResponse")]
        void closeAcc(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/closeAcc", ReplyAction="http://tempuri.org/IService/closeAccResponse")]
        System.Threading.Tasks.Task closeAccAsync(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/createProduct", ReplyAction="http://tempuri.org/IService/createProductResponse")]
        void createProduct(webapp_ui.ServiceReference1.Product product, int categoryId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/createProduct", ReplyAction="http://tempuri.org/IService/createProductResponse")]
        System.Threading.Tasks.Task createProductAsync(webapp_ui.ServiceReference1.Product product, int categoryId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getUser", ReplyAction="http://tempuri.org/IService/getUserResponse")]
        webapp_ui.ServiceReference1.User getUser(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getUser", ReplyAction="http://tempuri.org/IService/getUserResponse")]
        System.Threading.Tasks.Task<webapp_ui.ServiceReference1.User> getUserAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getUsers", ReplyAction="http://tempuri.org/IService/getUsersResponse")]
        webapp_ui.ServiceReference1.User[] getUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getUsers", ReplyAction="http://tempuri.org/IService/getUsersResponse")]
        System.Threading.Tasks.Task<webapp_ui.ServiceReference1.User[]> getUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getProduct", ReplyAction="http://tempuri.org/IService/getProductResponse")]
        webapp_ui.ServiceReference1.Product getProduct(System.Nullable<int> productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getProduct", ReplyAction="http://tempuri.org/IService/getProductResponse")]
        System.Threading.Tasks.Task<webapp_ui.ServiceReference1.Product> getProductAsync(System.Nullable<int> productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getProducts", ReplyAction="http://tempuri.org/IService/getProductsResponse")]
        webapp_ui.ServiceReference1.Product[] getProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getProducts", ReplyAction="http://tempuri.org/IService/getProductsResponse")]
        System.Threading.Tasks.Task<webapp_ui.ServiceReference1.Product[]> getProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getUserProducts", ReplyAction="http://tempuri.org/IService/getUserProductsResponse")]
        webapp_ui.ServiceReference1.Product[] getUserProducts(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getUserProducts", ReplyAction="http://tempuri.org/IService/getUserProductsResponse")]
        System.Threading.Tasks.Task<webapp_ui.ServiceReference1.Product[]> getUserProductsAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getCategoryProducts", ReplyAction="http://tempuri.org/IService/getCategoryProductsResponse")]
        webapp_ui.ServiceReference1.Product[] getCategoryProducts(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getCategoryProducts", ReplyAction="http://tempuri.org/IService/getCategoryProductsResponse")]
        System.Threading.Tasks.Task<webapp_ui.ServiceReference1.Product[]> getCategoryProductsAsync(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getCategoryProductsHighlow", ReplyAction="http://tempuri.org/IService/getCategoryProductsHighlowResponse")]
        webapp_ui.ServiceReference1.Product[] getCategoryProductsHighlow(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getCategoryProductsHighlow", ReplyAction="http://tempuri.org/IService/getCategoryProductsHighlowResponse")]
        System.Threading.Tasks.Task<webapp_ui.ServiceReference1.Product[]> getCategoryProductsHighlowAsync(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getCategoryProductsLowhigh", ReplyAction="http://tempuri.org/IService/getCategoryProductsLowhighResponse")]
        webapp_ui.ServiceReference1.Product[] getCategoryProductsLowhigh(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getCategoryProductsLowhigh", ReplyAction="http://tempuri.org/IService/getCategoryProductsLowhighResponse")]
        System.Threading.Tasks.Task<webapp_ui.ServiceReference1.Product[]> getCategoryProductsLowhighAsync(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getCategory", ReplyAction="http://tempuri.org/IService/getCategoryResponse")]
        webapp_ui.ServiceReference1.Category getCategory(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getCategory", ReplyAction="http://tempuri.org/IService/getCategoryResponse")]
        System.Threading.Tasks.Task<webapp_ui.ServiceReference1.Category> getCategoryAsync(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getCategories", ReplyAction="http://tempuri.org/IService/getCategoriesResponse")]
        webapp_ui.ServiceReference1.Category[] getCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getCategories", ReplyAction="http://tempuri.org/IService/getCategoriesResponse")]
        System.Threading.Tasks.Task<webapp_ui.ServiceReference1.Category[]> getCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/createCategory", ReplyAction="http://tempuri.org/IService/createCategoryResponse")]
        void createCategory(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/createCategory", ReplyAction="http://tempuri.org/IService/createCategoryResponse")]
        System.Threading.Tasks.Task createCategoryAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/createPriceOffer", ReplyAction="http://tempuri.org/IService/createPriceOfferResponse")]
        void createPriceOffer(webapp_ui.ServiceReference1.PriceOffer priceOffer, int prodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/createPriceOffer", ReplyAction="http://tempuri.org/IService/createPriceOfferResponse")]
        System.Threading.Tasks.Task createPriceOfferAsync(webapp_ui.ServiceReference1.PriceOffer priceOffer, int prodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/createReview", ReplyAction="http://tempuri.org/IService/createReviewResponse")]
        void createReview(int stars, string Comment, int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/createReview", ReplyAction="http://tempuri.org/IService/createReviewResponse")]
        System.Threading.Tasks.Task createReviewAsync(int stars, string Comment, int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditProduct", ReplyAction="http://tempuri.org/IService/EditProductResponse")]
        void EditProduct(webapp_ui.ServiceReference1.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditProduct", ReplyAction="http://tempuri.org/IService/EditProductResponse")]
        System.Threading.Tasks.Task EditProductAsync(webapp_ui.ServiceReference1.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditUser", ReplyAction="http://tempuri.org/IService/EditUserResponse")]
        void EditUser(webapp_ui.ServiceReference1.User appUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditUser", ReplyAction="http://tempuri.org/IService/EditUserResponse")]
        System.Threading.Tasks.Task EditUserAsync(webapp_ui.ServiceReference1.User appUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getUserAddress", ReplyAction="http://tempuri.org/IService/getUserAddressResponse")]
        webapp_ui.ServiceReference1.BillingAddress getUserAddress(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getUserAddress", ReplyAction="http://tempuri.org/IService/getUserAddressResponse")]
        System.Threading.Tasks.Task<webapp_ui.ServiceReference1.BillingAddress> getUserAddressAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateUserAddress", ReplyAction="http://tempuri.org/IService/CreateUserAddressResponse")]
        void CreateUserAddress(webapp_ui.ServiceReference1.BillingAddress billingAddress, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateUserAddress", ReplyAction="http://tempuri.org/IService/CreateUserAddressResponse")]
        System.Threading.Tasks.Task CreateUserAddressAsync(webapp_ui.ServiceReference1.BillingAddress billingAddress, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditAddress", ReplyAction="http://tempuri.org/IService/EditAddressResponse")]
        void EditAddress(webapp_ui.ServiceReference1.BillingAddress address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditAddress", ReplyAction="http://tempuri.org/IService/EditAddressResponse")]
        System.Threading.Tasks.Task EditAddressAsync(webapp_ui.ServiceReference1.BillingAddress address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getOrders", ReplyAction="http://tempuri.org/IService/getOrdersResponse")]
        webapp_ui.ServiceReference1.ORDER[] getOrders(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getOrders", ReplyAction="http://tempuri.org/IService/getOrdersResponse")]
        System.Threading.Tasks.Task<webapp_ui.ServiceReference1.ORDER[]> getOrdersAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/createOrder", ReplyAction="http://tempuri.org/IService/createOrderResponse")]
        void createOrder(string cartid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/createOrder", ReplyAction="http://tempuri.org/IService/createOrderResponse")]
        System.Threading.Tasks.Task createOrderAsync(string cartid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getPriceOffers", ReplyAction="http://tempuri.org/IService/getPriceOffersResponse")]
        webapp_ui.ServiceReference1.PriceOffer[] getPriceOffers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getPriceOffers", ReplyAction="http://tempuri.org/IService/getPriceOffersResponse")]
        System.Threading.Tasks.Task<webapp_ui.ServiceReference1.PriceOffer[]> getPriceOffersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getPriceOffer", ReplyAction="http://tempuri.org/IService/getPriceOfferResponse")]
        webapp_ui.ServiceReference1.PriceOffer getPriceOffer(int offerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getPriceOffer", ReplyAction="http://tempuri.org/IService/getPriceOfferResponse")]
        System.Threading.Tasks.Task<webapp_ui.ServiceReference1.PriceOffer> getPriceOfferAsync(int offerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditPriceOffer", ReplyAction="http://tempuri.org/IService/EditPriceOfferResponse")]
        void EditPriceOffer(webapp_ui.ServiceReference1.PriceOffer offer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditPriceOffer", ReplyAction="http://tempuri.org/IService/EditPriceOfferResponse")]
        System.Threading.Tasks.Task EditPriceOfferAsync(webapp_ui.ServiceReference1.PriceOffer offer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddToCart", ReplyAction="http://tempuri.org/IService/AddToCartResponse")]
        void AddToCart(webapp_ui.ServiceReference1.CartItem cartItem, int prodid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddToCart", ReplyAction="http://tempuri.org/IService/AddToCartResponse")]
        System.Threading.Tasks.Task AddToCartAsync(webapp_ui.ServiceReference1.CartItem cartItem, int prodid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getCartItems", ReplyAction="http://tempuri.org/IService/getCartItemsResponse")]
        webapp_ui.ServiceReference1.CartItem getCartItems(string cartId, int prodid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getCartItems", ReplyAction="http://tempuri.org/IService/getCartItemsResponse")]
        System.Threading.Tasks.Task<webapp_ui.ServiceReference1.CartItem> getCartItemsAsync(string cartId, int prodid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getCartListItems", ReplyAction="http://tempuri.org/IService/getCartListItemsResponse")]
        webapp_ui.ServiceReference1.CartItem[] getCartListItems(string cartId, int prodid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getCartListItems", ReplyAction="http://tempuri.org/IService/getCartListItemsResponse")]
        System.Threading.Tasks.Task<webapp_ui.ServiceReference1.CartItem[]> getCartListItemsAsync(string cartId, int prodid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/cartCount", ReplyAction="http://tempuri.org/IService/cartCountResponse")]
        int cartCount(string cartid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/cartCount", ReplyAction="http://tempuri.org/IService/cartCountResponse")]
        System.Threading.Tasks.Task<int> cartCountAsync(string cartid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/saleCount", ReplyAction="http://tempuri.org/IService/saleCountResponse")]
        int saleCount(int prodid, int uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/saleCount", ReplyAction="http://tempuri.org/IService/saleCountResponse")]
        System.Threading.Tasks.Task<int> saleCountAsync(int prodid, int uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getUserbyEmail", ReplyAction="http://tempuri.org/IService/getUserbyEmailResponse")]
        webapp_ui.ServiceReference1.User getUserbyEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getUserbyEmail", ReplyAction="http://tempuri.org/IService/getUserbyEmailResponse")]
        System.Threading.Tasks.Task<webapp_ui.ServiceReference1.User> getUserbyEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/deleteCartItem", ReplyAction="http://tempuri.org/IService/deleteCartItemResponse")]
        void deleteCartItem(int cid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/deleteCartItem", ReplyAction="http://tempuri.org/IService/deleteCartItemResponse")]
        System.Threading.Tasks.Task deleteCartItemAsync(int cid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/deleteorder", ReplyAction="http://tempuri.org/IService/deleteorderResponse")]
        void deleteorder(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/deleteorder", ReplyAction="http://tempuri.org/IService/deleteorderResponse")]
        System.Threading.Tasks.Task deleteorderAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/deletepriceoffer", ReplyAction="http://tempuri.org/IService/deletepriceofferResponse")]
        void deletepriceoffer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/deletepriceoffer", ReplyAction="http://tempuri.org/IService/deletepriceofferResponse")]
        System.Threading.Tasks.Task deletepriceofferAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/deleteproduct", ReplyAction="http://tempuri.org/IService/deleteproductResponse")]
        void deleteproduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/deleteproduct", ReplyAction="http://tempuri.org/IService/deleteproductResponse")]
        System.Threading.Tasks.Task deleteproductAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getOrdersUserIsBought", ReplyAction="http://tempuri.org/IService/getOrdersUserIsBoughtResponse")]
        webapp_ui.ServiceReference1.ORDER[] getOrdersUserIsBought(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getOrdersUserIsBought", ReplyAction="http://tempuri.org/IService/getOrdersUserIsBoughtResponse")]
        System.Threading.Tasks.Task<webapp_ui.ServiceReference1.ORDER[]> getOrdersUserIsBoughtAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/updateOrderIsAlreadyBought", ReplyAction="http://tempuri.org/IService/updateOrderIsAlreadyBoughtResponse")]
        void updateOrderIsAlreadyBought(int userid, int prodid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/updateOrderIsAlreadyBought", ReplyAction="http://tempuri.org/IService/updateOrderIsAlreadyBoughtResponse")]
        System.Threading.Tasks.Task updateOrderIsAlreadyBoughtAsync(int userid, int prodid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/updateQty", ReplyAction="http://tempuri.org/IService/updateQtyResponse")]
        void updateQty(string cartid, int prodid, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/updateQty", ReplyAction="http://tempuri.org/IService/updateQtyResponse")]
        System.Threading.Tasks.Task updateQtyAsync(string cartid, int prodid, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/updateOrderIsBought", ReplyAction="http://tempuri.org/IService/updateOrderIsBoughtResponse")]
        void updateOrderIsBought(int userid, int prodid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/updateOrderIsBought", ReplyAction="http://tempuri.org/IService/updateOrderIsBoughtResponse")]
        System.Threading.Tasks.Task updateOrderIsBoughtAsync(int userid, int prodid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/searchresults", ReplyAction="http://tempuri.org/IService/searchresultsResponse")]
        webapp_ui.ServiceReference1.Product[] searchresults(string searchvalue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/searchresults", ReplyAction="http://tempuri.org/IService/searchresultsResponse")]
        System.Threading.Tasks.Task<webapp_ui.ServiceReference1.Product[]> searchresultsAsync(string searchvalue);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : webapp_ui.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<webapp_ui.ServiceReference1.IService>, webapp_ui.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Register(webapp_ui.ServiceReference1.User user) {
            return base.Channel.Register(user);
        }
        
        public System.Threading.Tasks.Task<int> RegisterAsync(webapp_ui.ServiceReference1.User user) {
            return base.Channel.RegisterAsync(user);
        }
        
        public bool Login(string Email, string Password) {
            return base.Channel.Login(Email, Password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string Email, string Password) {
            return base.Channel.LoginAsync(Email, Password);
        }
        
        public void closeAcc(string Email, string Password) {
            base.Channel.closeAcc(Email, Password);
        }
        
        public System.Threading.Tasks.Task closeAccAsync(string Email, string Password) {
            return base.Channel.closeAccAsync(Email, Password);
        }
        
        public void createProduct(webapp_ui.ServiceReference1.Product product, int categoryId, int userId) {
            base.Channel.createProduct(product, categoryId, userId);
        }
        
        public System.Threading.Tasks.Task createProductAsync(webapp_ui.ServiceReference1.Product product, int categoryId, int userId) {
            return base.Channel.createProductAsync(product, categoryId, userId);
        }
        
        public webapp_ui.ServiceReference1.User getUser(int userId) {
            return base.Channel.getUser(userId);
        }
        
        public System.Threading.Tasks.Task<webapp_ui.ServiceReference1.User> getUserAsync(int userId) {
            return base.Channel.getUserAsync(userId);
        }
        
        public webapp_ui.ServiceReference1.User[] getUsers() {
            return base.Channel.getUsers();
        }
        
        public System.Threading.Tasks.Task<webapp_ui.ServiceReference1.User[]> getUsersAsync() {
            return base.Channel.getUsersAsync();
        }
        
        public webapp_ui.ServiceReference1.Product getProduct(System.Nullable<int> productId) {
            return base.Channel.getProduct(productId);
        }
        
        public System.Threading.Tasks.Task<webapp_ui.ServiceReference1.Product> getProductAsync(System.Nullable<int> productId) {
            return base.Channel.getProductAsync(productId);
        }
        
        public webapp_ui.ServiceReference1.Product[] getProducts() {
            return base.Channel.getProducts();
        }
        
        public System.Threading.Tasks.Task<webapp_ui.ServiceReference1.Product[]> getProductsAsync() {
            return base.Channel.getProductsAsync();
        }
        
        public webapp_ui.ServiceReference1.Product[] getUserProducts(int userId) {
            return base.Channel.getUserProducts(userId);
        }
        
        public System.Threading.Tasks.Task<webapp_ui.ServiceReference1.Product[]> getUserProductsAsync(int userId) {
            return base.Channel.getUserProductsAsync(userId);
        }
        
        public webapp_ui.ServiceReference1.Product[] getCategoryProducts(int categoryId) {
            return base.Channel.getCategoryProducts(categoryId);
        }
        
        public System.Threading.Tasks.Task<webapp_ui.ServiceReference1.Product[]> getCategoryProductsAsync(int categoryId) {
            return base.Channel.getCategoryProductsAsync(categoryId);
        }
        
        public webapp_ui.ServiceReference1.Product[] getCategoryProductsHighlow(int categoryId) {
            return base.Channel.getCategoryProductsHighlow(categoryId);
        }
        
        public System.Threading.Tasks.Task<webapp_ui.ServiceReference1.Product[]> getCategoryProductsHighlowAsync(int categoryId) {
            return base.Channel.getCategoryProductsHighlowAsync(categoryId);
        }
        
        public webapp_ui.ServiceReference1.Product[] getCategoryProductsLowhigh(int categoryId) {
            return base.Channel.getCategoryProductsLowhigh(categoryId);
        }
        
        public System.Threading.Tasks.Task<webapp_ui.ServiceReference1.Product[]> getCategoryProductsLowhighAsync(int categoryId) {
            return base.Channel.getCategoryProductsLowhighAsync(categoryId);
        }
        
        public webapp_ui.ServiceReference1.Category getCategory(int categoryId) {
            return base.Channel.getCategory(categoryId);
        }
        
        public System.Threading.Tasks.Task<webapp_ui.ServiceReference1.Category> getCategoryAsync(int categoryId) {
            return base.Channel.getCategoryAsync(categoryId);
        }
        
        public webapp_ui.ServiceReference1.Category[] getCategories() {
            return base.Channel.getCategories();
        }
        
        public System.Threading.Tasks.Task<webapp_ui.ServiceReference1.Category[]> getCategoriesAsync() {
            return base.Channel.getCategoriesAsync();
        }
        
        public void createCategory(string name) {
            base.Channel.createCategory(name);
        }
        
        public System.Threading.Tasks.Task createCategoryAsync(string name) {
            return base.Channel.createCategoryAsync(name);
        }
        
        public void createPriceOffer(webapp_ui.ServiceReference1.PriceOffer priceOffer, int prodId) {
            base.Channel.createPriceOffer(priceOffer, prodId);
        }
        
        public System.Threading.Tasks.Task createPriceOfferAsync(webapp_ui.ServiceReference1.PriceOffer priceOffer, int prodId) {
            return base.Channel.createPriceOfferAsync(priceOffer, prodId);
        }
        
        public void createReview(int stars, string Comment, int productId) {
            base.Channel.createReview(stars, Comment, productId);
        }
        
        public System.Threading.Tasks.Task createReviewAsync(int stars, string Comment, int productId) {
            return base.Channel.createReviewAsync(stars, Comment, productId);
        }
        
        public void EditProduct(webapp_ui.ServiceReference1.Product product) {
            base.Channel.EditProduct(product);
        }
        
        public System.Threading.Tasks.Task EditProductAsync(webapp_ui.ServiceReference1.Product product) {
            return base.Channel.EditProductAsync(product);
        }
        
        public void EditUser(webapp_ui.ServiceReference1.User appUser) {
            base.Channel.EditUser(appUser);
        }
        
        public System.Threading.Tasks.Task EditUserAsync(webapp_ui.ServiceReference1.User appUser) {
            return base.Channel.EditUserAsync(appUser);
        }
        
        public webapp_ui.ServiceReference1.BillingAddress getUserAddress(int userId) {
            return base.Channel.getUserAddress(userId);
        }
        
        public System.Threading.Tasks.Task<webapp_ui.ServiceReference1.BillingAddress> getUserAddressAsync(int userId) {
            return base.Channel.getUserAddressAsync(userId);
        }
        
        public void CreateUserAddress(webapp_ui.ServiceReference1.BillingAddress billingAddress, int userId) {
            base.Channel.CreateUserAddress(billingAddress, userId);
        }
        
        public System.Threading.Tasks.Task CreateUserAddressAsync(webapp_ui.ServiceReference1.BillingAddress billingAddress, int userId) {
            return base.Channel.CreateUserAddressAsync(billingAddress, userId);
        }
        
        public void EditAddress(webapp_ui.ServiceReference1.BillingAddress address) {
            base.Channel.EditAddress(address);
        }
        
        public System.Threading.Tasks.Task EditAddressAsync(webapp_ui.ServiceReference1.BillingAddress address) {
            return base.Channel.EditAddressAsync(address);
        }
        
        public webapp_ui.ServiceReference1.ORDER[] getOrders(int userId) {
            return base.Channel.getOrders(userId);
        }
        
        public System.Threading.Tasks.Task<webapp_ui.ServiceReference1.ORDER[]> getOrdersAsync(int userId) {
            return base.Channel.getOrdersAsync(userId);
        }
        
        public void createOrder(string cartid) {
            base.Channel.createOrder(cartid);
        }
        
        public System.Threading.Tasks.Task createOrderAsync(string cartid) {
            return base.Channel.createOrderAsync(cartid);
        }
        
        public webapp_ui.ServiceReference1.PriceOffer[] getPriceOffers() {
            return base.Channel.getPriceOffers();
        }
        
        public System.Threading.Tasks.Task<webapp_ui.ServiceReference1.PriceOffer[]> getPriceOffersAsync() {
            return base.Channel.getPriceOffersAsync();
        }
        
        public webapp_ui.ServiceReference1.PriceOffer getPriceOffer(int offerid) {
            return base.Channel.getPriceOffer(offerid);
        }
        
        public System.Threading.Tasks.Task<webapp_ui.ServiceReference1.PriceOffer> getPriceOfferAsync(int offerid) {
            return base.Channel.getPriceOfferAsync(offerid);
        }
        
        public void EditPriceOffer(webapp_ui.ServiceReference1.PriceOffer offer) {
            base.Channel.EditPriceOffer(offer);
        }
        
        public System.Threading.Tasks.Task EditPriceOfferAsync(webapp_ui.ServiceReference1.PriceOffer offer) {
            return base.Channel.EditPriceOfferAsync(offer);
        }
        
        public void AddToCart(webapp_ui.ServiceReference1.CartItem cartItem, int prodid) {
            base.Channel.AddToCart(cartItem, prodid);
        }
        
        public System.Threading.Tasks.Task AddToCartAsync(webapp_ui.ServiceReference1.CartItem cartItem, int prodid) {
            return base.Channel.AddToCartAsync(cartItem, prodid);
        }
        
        public webapp_ui.ServiceReference1.CartItem getCartItems(string cartId, int prodid) {
            return base.Channel.getCartItems(cartId, prodid);
        }
        
        public System.Threading.Tasks.Task<webapp_ui.ServiceReference1.CartItem> getCartItemsAsync(string cartId, int prodid) {
            return base.Channel.getCartItemsAsync(cartId, prodid);
        }
        
        public webapp_ui.ServiceReference1.CartItem[] getCartListItems(string cartId, int prodid) {
            return base.Channel.getCartListItems(cartId, prodid);
        }
        
        public System.Threading.Tasks.Task<webapp_ui.ServiceReference1.CartItem[]> getCartListItemsAsync(string cartId, int prodid) {
            return base.Channel.getCartListItemsAsync(cartId, prodid);
        }
        
        public int cartCount(string cartid) {
            return base.Channel.cartCount(cartid);
        }
        
        public System.Threading.Tasks.Task<int> cartCountAsync(string cartid) {
            return base.Channel.cartCountAsync(cartid);
        }
        
        public int saleCount(int prodid, int uid) {
            return base.Channel.saleCount(prodid, uid);
        }
        
        public System.Threading.Tasks.Task<int> saleCountAsync(int prodid, int uid) {
            return base.Channel.saleCountAsync(prodid, uid);
        }
        
        public webapp_ui.ServiceReference1.User getUserbyEmail(string email) {
            return base.Channel.getUserbyEmail(email);
        }
        
        public System.Threading.Tasks.Task<webapp_ui.ServiceReference1.User> getUserbyEmailAsync(string email) {
            return base.Channel.getUserbyEmailAsync(email);
        }
        
        public void deleteCartItem(int cid) {
            base.Channel.deleteCartItem(cid);
        }
        
        public System.Threading.Tasks.Task deleteCartItemAsync(int cid) {
            return base.Channel.deleteCartItemAsync(cid);
        }
        
        public void deleteorder(int id) {
            base.Channel.deleteorder(id);
        }
        
        public System.Threading.Tasks.Task deleteorderAsync(int id) {
            return base.Channel.deleteorderAsync(id);
        }
        
        public void deletepriceoffer(int id) {
            base.Channel.deletepriceoffer(id);
        }
        
        public System.Threading.Tasks.Task deletepriceofferAsync(int id) {
            return base.Channel.deletepriceofferAsync(id);
        }
        
        public void deleteproduct(int id) {
            base.Channel.deleteproduct(id);
        }
        
        public System.Threading.Tasks.Task deleteproductAsync(int id) {
            return base.Channel.deleteproductAsync(id);
        }
        
        public webapp_ui.ServiceReference1.ORDER[] getOrdersUserIsBought(int userId) {
            return base.Channel.getOrdersUserIsBought(userId);
        }
        
        public System.Threading.Tasks.Task<webapp_ui.ServiceReference1.ORDER[]> getOrdersUserIsBoughtAsync(int userId) {
            return base.Channel.getOrdersUserIsBoughtAsync(userId);
        }
        
        public void updateOrderIsAlreadyBought(int userid, int prodid) {
            base.Channel.updateOrderIsAlreadyBought(userid, prodid);
        }
        
        public System.Threading.Tasks.Task updateOrderIsAlreadyBoughtAsync(int userid, int prodid) {
            return base.Channel.updateOrderIsAlreadyBoughtAsync(userid, prodid);
        }
        
        public void updateQty(string cartid, int prodid, int quantity) {
            base.Channel.updateQty(cartid, prodid, quantity);
        }
        
        public System.Threading.Tasks.Task updateQtyAsync(string cartid, int prodid, int quantity) {
            return base.Channel.updateQtyAsync(cartid, prodid, quantity);
        }
        
        public void updateOrderIsBought(int userid, int prodid) {
            base.Channel.updateOrderIsBought(userid, prodid);
        }
        
        public System.Threading.Tasks.Task updateOrderIsBoughtAsync(int userid, int prodid) {
            return base.Channel.updateOrderIsBoughtAsync(userid, prodid);
        }
        
        public webapp_ui.ServiceReference1.Product[] searchresults(string searchvalue) {
            return base.Channel.searchresults(searchvalue);
        }
        
        public System.Threading.Tasks.Task<webapp_ui.ServiceReference1.Product[]> searchresultsAsync(string searchvalue) {
            return base.Channel.searchresultsAsync(searchvalue);
        }
    }
}
